const TEAM_DATA = [
    {
        id: 7,
          title: 'Eastern Conference Standings',
          routeName: 'ecf',
          items: [
          {
            teamName: 'Milwaukee Bucks',
            wins: '13',
            losses: '3',
            wlpct: '.813',
            gb: '--',
            stat: 'ECF',
            rank: '1',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/MIL.svg',
            id: 61,
          },
          {
            teamName: 'Boston Celtics',
            wins: '11',
            losses: '4',
            wlpct: '.733',
            gb: '1.5',
            stat: 'ECF',
            rank: '2',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/BOS.svg',
            id: 63,
          },
          {
            teamName: 'Toronto Raptors',
            wins: '11',
            losses: '4',
            wlpct: '.733',
            gb: '1.5',
            stat: 'ECF',
            rank: '3',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/TOR.svg',
            id: 64,
          },
          {
            teamName: 'Miami Heat',
            wins: '11',
            losses: '4',
            wlpct: '.733',
            gb: '1.5',
            stat: 'ECF',
            rank: '4',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/MIA.svg',
            id: 62,
          },
          {
            teamName: 'Philadelphia 76ers',
            wins: '11',
            losses: '5',
            wlpct: '.688',
            gb: '2.0',
            stat: 'ECF',
            rank: '5',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/PHI.svg',
            id: 65,
          },
          {
            teamName: 'Indiana Pacers',
            wins: '9',
            losses: '6',
            wlpct: '.600',
            gb: '3.5',
            stat: 'ECF',
            rank: '6',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/IND.svg',
            id: 66,
          },
          {
            teamName: 'Brooklyn Nets',
            wins: '8',
            losses: '8',
            wlpct: '.500',
            gb: '5.0',
            stat: 'ECF',
            rank: '7',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/BKN.svg',
            id: 67,
          },
          {
            teamName: 'Orlando Magic',
            wins: '6',
            losses: '9',
            wlpct: '.400',
            gb: '6.5',
            stat: 'ECF',
            rank: '8',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/ORL.svg',
            id: 68,
          },
          {
            teamName: 'Washington Wizards',
            wins: '5',
            losses: '9',
            wlpct: '.357',
            gb: '7.0',
            stat: 'ECF',
            rank: '9',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/WAS.svg',
            id: 69,
          },
          {
            teamName: 'Charlotte Hornets',
            wins: '6',
            losses: '11',
            wlpct: '.353',
            gb: '7.5',
            stat: 'ECF',
            rank: '10',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/CHA.svg',
            id: 70,
          },
          {
            teamName: 'Chicago Bulls',
            wins: '6',
            losses: '11',
            wlpct: '.353',
            gb: '7.5',
            stat: 'ECF',
            rank: '11',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/CHI.svg',
            id: 72,
          },
          {
            teamName: 'Cleveland Cavaliers',
            wins: '5',
            losses: '11',
            wlpct: '.313',
            gb: '8.0',
            stat: 'ECF',
            rank: '12',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/CLE.svg',
            id: 73,
          },
          {
            teamName: 'Detroit Pistons',
            wins: '5',
            losses: '11',
            wlpct: '.313',
            gb: '8.0',
            stat: 'ECF',
            rank: '13',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/DET.svg',
            id: 71,
          },
          {
            teamName: 'Atlanta Hawks',
            wins: '4',
            losses: '12',
            wlpct: '.250',
            gb: '9.0',
            stat: 'ECF',
            rank: '14',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/ATL.svg',
            id: 75,
          },
          {
            teamName: 'New York Knicks',
            wins: '4',
            losses: '13',
            wlpct: '.235',
            gb: '9.5',
            stat: 'ECF',
            rank: '15',
            imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/NYK.svg',
            id: 74,
          },
          ]
        },
        {
          id: 8,
            title: 'Western Conference Standings',
            routeName: 'wcf',
            items: [
            {
              teamName: 'Los Angeles Lakers',
              wins: '14',
              losses: '2',
              wlpct: '.875',
              gb: '--',
              stat: 'WCF',
              rank: '1',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/LAL.svg',
              id: 76,
            },
            {
              teamName: 'Denver Nuggets',
              wins: '12',
              losses: '3',
              wlpct: '.800',
              gb: '1.5',
              stat: 'WCF',
              rank: '2',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/DEN.svg',
              id: 77,
            },
            {
              teamName: 'Los Angeles Clippers',
              wins: '12',
              losses: '5',
              wlpct: '.706',
              gb: '2.5',
              stat: 'WCF',
              rank: '3',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/LAC.svg',
              id: 78,
            },
            {
              teamName: 'Utah Jazz',
              wins: '11',
              losses: '5',
              wlpct: '6.88',
              gb: '3.0',
              stat: 'WCF',
              rank: '4',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/UTA.svg',
              id: 81,
            },
            {
              teamName: 'Dallas Mavericks',
              wins: '11',
              losses: '5',
              wlpct: '.688',
              gb: '3.0',
              stat: 'WCF',
              rank: '5',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/DAL.svg',
              id: 80,
            },
            {
              teamName: 'Houston Rockets',
              wins: '11',
              losses: '6',
              wlpct: '.647',
              gb: '3.5',
              stat: 'WCF',
              rank: '6',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/HOU.svg',
              id: 79,
            },
            {
              teamName: 'Minnesota Timberwolves',
              wins: '8',
              losses: '8',
              wlpct: '.500',
              gb: '6.0',
              stat: 'WCF',
              rank: '7',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/MIN.svg',
              id: 82,
            },
            {
              teamName: 'Phoenix Suns',
              wins: '8',
              losses: '8',
              wlpct: '.500',
              gb: '6.0',
              stat: 'WCF',
              rank: '8',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/PHX.svg',
              id: 83,
            },
            {
              teamName: 'Sacramento Kings',
              wins: '7',
              losses: '8',
              wlpct: '.467',
              gb: '6.5',
              stat: 'WCF',
              rank: '9',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/SAC.svg',
              id: 84,
            },
            {
              teamName: 'New Orleans Pelicans',
              wins: '6',
              losses: '11',
              wlpct: '.353',
              gb: '8.5',
              stat: 'WCF',
              rank: '10',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/NOP.svg',
              id: 85,
            },
            {
              teamName: 'San Antonio Spurs',
              wins: '6',
              losses: '11',
              wlpct: '.353',
              gb: '8.5',
              stat: 'WCF',
              rank: '11',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/SAS.svg',
              id: 88,
            },
            {
              teamName: 'Oklahoma City Thunder',
              wins: '5',
              losses: '10',
              wlpct: '.333',
              gb: '8.5',
              stat: 'WCF',
              rank: '12',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/OKC.svg',
              id: 87,
            },
            {
              teamName: 'Memphis Grizzlies',
              wins: '5',
              losses: '9',
              wlpct: '.333',
              gb: '8.5',
              stat: 'WCF',
              rank: '13',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/MEM.svg',
              id: 86,
            },
            {
              teamName: 'Portland Trail Blazers',
              wins: '5',
              losses: '12',
              wlpct: '.294',
              gb: '9.5',
              stat: 'WCF',
              rank: '14',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/POR.svg',
              id: 89,
            },
            {
              teamName: 'Golden State Warriors',
              wins: '3',
              losses: '14',
              wlpct: '.176',
              gb: '11.5',
              stat: 'WCF',
              rank: '15',
              imageUrl: 'https://www.nba.com/assets/logos/teams/primary/web/GSW.svg',
              id: 90,
            }
        ]
    }
];

export default TEAM_DATA;