const NBA_DATA = [
  {
    id: 1,
    title: 'Points per game',
    routeName: 'ppg',
    items: [
      {
        name: 'James Harden',
        teamName: 'HOU',
        stat: 'PPG',
        perGame: '30.3',
        rank: '1',
        imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201935.png',
        id: 1,
      },
      {
        name: 'Bradley Beal',
        teamName: 'WAS',
        stat: 'PPG',
        perGame: '30.3',
        rank: '2',
        imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203078.png',
        id: 2,
      },
      {
        name: 'Giannis Antetokounmpo',
        teamName: 'MIL',
        stat: 'PPG',
        perGame: '30.1',
        rank: '3',
        imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203507.png',
        id: 3,
      },
      {
        name: 'Luka Dončić',
        teamName: 'DAL',
        stat: 'PPG',
        perGame: '29.9',
        rank: '4',
        imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1629029.png',
        id: 4,
      },
      {
        name: 'Damian Lillard',
        teamName: 'POR',
        stat: 'PPG',
        perGame: '28.6',
        rank: '5',
        imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203081.png',
        id: 5,
      },
      {
        name: 'Kyrie Irving',
        teamName: 'BRK',
        stat: 'PPG',
        perGame: '28.5',
        rank: '6',
        imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/202681.png',
        id: 6,
      },
      {
        name: 'Karl-Anthony Towns',
        teamName: 'MIN',
        stat: 'PPG',
        perGame: '26.0',
        rank: '7',
        imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1626157.png',
        id: 7,
      },
      {
        name: 'Anthony Davis',
        teamName: 'LAL',
        stat: 'PPG',
        perGame: '25.8',
        rank: '8',
        imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203076.png',
        id: 8,
      },
      {
        name: 'Brandon Ingram',
        teamName: 'NOP',
        stat: 'PPG',
        perGame: '25.6',
        rank: '9',
        imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1627742.png',
        id: 9,
      },
      {
        name: 'Kawhi Leonard',
        teamName: 'LAC',
        stat: 'PPG',
        perGame: '25.6',
        rank: '10',
        imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/202695.png',
        id: 10,
      } 
    ]
  },
  {
  id: 2,
  title: 'Assists per game',
  routeName: 'apg',
  items: [
    {
      name: 'LeBron James',
      teamName: 'LAL',
      stat: 'APG',
      perGame: '11.3',
      rank: '1',
      imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/2544.png',
      id: 11,
    },
    {
      name: 'Luka Dončić',
      teamName: 'DAL',
      stat: 'APG',
      perGame: '9.7',
      rank: '2',
      imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1629029.png',
      id: 12,
    },
    {
      name: 'Trae Young',
      teamName: 'ATL',
      stat: 'APG',
      perGame: '8.6',
      rank: '3',
      imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1629027.png',
      id: 13,
    },
    {
      name: 'Malcolm Brogdon',
      teamName: 'IND',
      stat: 'APG',
      perGame: '8.2',
      rank: '4',
      imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1627763.png',
      id: 14,
    },
    {
      name: 'Ricky Rubio',
      teamName: 'PHO',
      stat: 'APG',
      perGame: '8.1',
      rank: '5',
      imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201937.png',
      id: 15,
    },
    {
      name: 'Ben Simmons',
      teamName: 'PHI',
      stat: 'APG',
      perGame: '8.0',
      rank: '6',
      imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1627732.png',
      id: 16,
    },
    {
      name: 'James Harden',
      teamName: 'HOU',
      stat: 'APG',
      perGame: '7.8',
      rank: '7',
      imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201935.png',
      id: 17,
    },
    {
      name: 'Jeff Teague',
      teamName: 'MIN',
      stat: 'APG',
      perGame: '7.6',
      rank: '8',
      imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201952.png',
      id: 18,
    },
    {
      name: 'Fred VanVleet',
      teamName: 'TOR',
      stat: 'APG',
      perGame: '7.6',
      rank: '9',
      imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1627832.png',
      id: 19,
    },
    {
      name: 'Jrue Holiday',
      teamName: 'NOP',
      stat: 'APG',
      perGame: '7.5',
      rank: '10',
      imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201950.png',
      id: 20,
    }
  ]
},
{
id: 3,
  title: 'Rebounds per game',
  routeName: 'rpg',
  items: [
    {
    name: 'Andre Drummond',
    teamName: 'DET',
    stat: 'RPG',
    perGame: '16.7',
    rank: '1',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203083.png',
    id: 21,
  },
  {
    name: 'Giannis Antetokounmpo',
    teamName: 'MIL',
    stat: 'RPG',
    perGame: '14.1',
    rank: '2',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203507.png',
    id: 22,
  },
  {
    name: 'Clint Capela',
    teamName: 'HOU',
    stat: 'RPG',
    perGame: '14.1',
    rank: '3',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203991.png',
    id: 23,
  },
  {
    name: 'Rudy Gobert',
    teamName: 'UTA',
    stat: 'RPG',
    perGame: '14.1',
    rank: '4',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203497.png',
    id: 24,
  },
  {
    name: 'Domantas Sabonis',
    teamName: 'IND',
    stat: 'RPG',
    perGame: '13.8',
    rank: '5',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1627734.png',
    id: 25,
  },
  {
    name: 'Karl-Anthony Towns',
    teamName: 'MIN',
    stat: 'RPG',
    perGame: '12.1',
    rank: '6',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1626157.png',
    id: 26,
  },
  {
    name: 'Hassan Whiteside',
    teamName: 'POR',
    stat: 'RPG',
    perGame: '12.0',
    rank: '7',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/202355.png',
    id: 27,
  },
  {
    name: 'Kevin Love',
    teamName: 'CLE',
    stat: 'RPG',
    perGame: '11.8',
    rank: '8',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201567.png',
    id: 28,
  },
  {
    name: 'Joel Embiid',
    teamName: 'PHI',
    stat: 'RPG',
    perGame: '11.7',
    rank: '9',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203954.png',
    id: 29,
  },
  {
    name: 'Nikola Vučević',
    teamName: 'ORL',
    stat: 'RPG',
    perGame: '11.6',
    rank: '10',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/202696.png',
    id: 30,

    }
  ]
},
{
id: 4,
  title: 'Steals per game',
  routeName: 'spg',
  items: [
  {
    name: 'Jimmy Butler',
    teamName: 'MIA',
    stat: 'RPG',
    perGame: '2.8',
    rank: '1',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/202710.png',
    id: 31,
  },
  {
    name: 'Kawhi Leonard',
    teamName: 'LAC',
    stat: 'RPG',
    perGame: '2.3',
    rank: '2',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/202695.png',
    id: 32,
  },
  {
    name: 'Kris Dunn',
    teamName: 'CHI',
    stat: 'RPG',
    perGame: '2.2',
    rank: '3',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1627739.png',
    id: 33,
  },
  {
    name: 'Ben Simmons',
    teamName: 'PHI',
    stat: 'RPG',
    perGame: '2.2',
    rank: '4',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1627732.png',
    id: 34,
  },
  {
    name: 'Jrue Holiday',
    teamName: 'NOP',
    stat: 'RPG',
    perGame: '2.1',
    rank: '5',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201950.png',
    id: 35,
  },
  {
    name: 'Chris Paul',
    teamName: 'OKC',
    stat: 'RPG',
    perGame: '1.9',
    rank: '6',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/101108.png',
    id: 36,
  },
  {
    name: 'Fred VanVleet',
    teamName: 'TOR',
    stat: 'RPG',
    perGame: '1.9',
    rank: '7',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1627832.png',
    id: 37,
  },
  {
    name: 'Bam Adebayo',
    teamName: 'MIA',
    stat: 'RPG',
    perGame: '1.8',
    rank: '8',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1628389.png',
    id: 38,
  },
  {
    name: 'James Harden',
    teamName: 'HOU',
    stat: 'RPG',
    perGame: '1.7',
    rank: '9',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201935.png',
    id: 39,
  },
  {
    name: 'Andre Drummond',
    teamName: 'DET',
    stat: 'RPG',
    perGame: '1.7',
    rank: '10',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203083.png',
    id: 40,

    }
  ]
},
{
id: 5,
  title: 'Blocks per game',
  routeName: 'bpg',
  items: [
  {
    name: 'Anthony Davis',
    teamName: 'LAL',
    stat: 'RPG',
    perGame: '2.9',
    rank: '1',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203076.png',
    id: 41,
  },
  {
    name: 'Jonathan Isaac',
    teamName: 'ORL',
    stat: 'RPG',
    perGame: '2.8',
    rank: '2',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1628371.png',
    id: 42,
  },
  {
    name: 'Brook Lopez',
    teamName: 'MIL',
    stat: 'RPG',
    perGame: '2.4',
    rank: '3',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201572.png',
    id: 43,
  },
  {
    name: 'Kristaps Porziņģis',
    teamName: 'DAL',
    stat: 'RPG',
    perGame: '2.3',
    rank: '4',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/204001.png',
    id: 44,
  },
  {
    name: 'Clint Capela',
    teamName: 'HOU',
    stat: 'RPG',
    perGame: '2.1',
    rank: '5',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203991.png',
    id: 45,
  },
  {
    name: 'Rudy Gobert',
    teamName: 'UTA',
    stat: 'RPG',
    perGame: '2.1',
    rank: '6',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203497.png',
    id: 46,
  },
  {
    name: 'Andre Drummond',
    teamName: 'DET',
    stat: 'RPG',
    perGame: '2.0',
    rank: '7',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203083.png',
    id: 47,
  },
  {
    name: 'Mitchell Robinson',
    teamName: 'NYK',
    stat: 'RPG',
    perGame: '2.0',
    rank: '8',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1629011.png',
    id: 48,
  },
  {
    name: 'LaMarcus Aldridge',
    teamName: 'SAS',
    stat: 'RPG',
    perGame: '1.9',
    rank: '9',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/200746.png',
    id: 49,
  },
  {
    name: 'Hassan Whiteside',
    teamName: 'POR',
    stat: 'RPG',
    perGame: '1.8',
    rank: '10',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/202355.png',
    id: 50,
    }
  ]
},
{
id: 6,
  title: 'Player efficiency rating',
  routeName: 'per',
  items: [
  {
    name: 'Luka Dončić',
    teamName: 'DAL',
    stat: 'PER',
    perGame: '33.2',
    rank: '1',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203076.png',
    id: 51,
  },
  {
    name: 'Giannis Antetokounmpo',
    teamName: 'MIL',
    stat: 'PER',
    perGame: '31.9',
    rank: '2',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1628371.png',
    id: 52,
  },
  {
    name: 'James Harden',
    teamName: 'HOU',
    stat: 'PER',
    perGame: '30.9',
    rank: '3',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201572.png',
    id: 53,
  },
  {
    name: 'Karl-Anthony Towns',
    teamName: 'MIN',
    stat: 'PER',
    perGame: '29.1',
    rank: '4',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/204001.png',
    id: 54,
  },
  {
    name: 'LeBron James',
    teamName: 'LAL',
    stat: 'PER',
    perGame: '27.7',
    rank: '5',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203991.png',
    id: 55,
  },
  {
    name: 'Anthony Davis',
    teamName: 'LAL',
    stat: 'PER',
    perGame: '27.1',
    rank: '6',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203497.png',
    id: 56,
  },
  {
    name: 'Ivica Zubac',
    teamName: 'LAC',
    stat: 'PER',
    perGame: '26.2',
    rank: '7',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203083.png',
    id: 57,
  },
  {
    name: 'Kyrie Irving',
    teamName: 'BRK',
    stat: 'PER',
    perGame: '26.2',
    rank: '8',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1629011.png',
    id: 58,
  },
  {
    name: 'Joel Embiid',
    teamName: 'PHI',
    stat: 'PER',
    perGame: '25.9',
    rank: '9',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/200746.png',
    id: 59,
  },
  {
    name: 'Damian Lillard',
    teamName: 'POR',
    stat: 'PER',
    perGame: '25.5',
    rank: '10',
    imageUrl: 'https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/202355.png',
    id: 60,
    }
    ]
  }
];

export default NBA_DATA;